# Generated by Django 5.0.7 on 2025-05-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_malicious', models.BooleanField()),
                ('data', models.JSONField()),
                ('blocked', models.BooleanField(default=False)),
            ],
        ),
    ]
