# Generated by Django 5.0.7 on 2025-05-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficlog',
            old_name='data',
            new_name='raw_data',
        ),
        migrations.RemoveField(
            model_name='trafficlog',
            name='is_malicious',
        ),
        migrations.AddField(
            model_name='trafficlog',
            name='attack_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
